### ISSUE TITLE
TSPY package

### ISSUE THREAD

**Issue by elmiraberjisian** [Lab-ANT/Time2State#1]
Hi thank you for providing this package. I have read your paper (https://dl.acm.org/doi/abs/10.1145/3588697) and Im interested in applying it onto my data along with baseline algorithms. However, Ive recieved this error:
Warning: Permanently added 'github.com,140.82.114.4' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
When trying to install tspy (git clone git@github.com:Lab-ANT/TSpy)
I appreciate it if you could please help me with this.

**Comment by AprilCal** [comment]
> 

Hi，

Have you tried to clone through https protocol? i.e., git clone https://github.com/Lab-ANT/TSpy
You may also manually download the package through the download button on the project page.
This link may be helpful to you.  https://github.com/facebookresearch/deepmask/issues/23

By the way, please switch to the dev branch of TSpy.
I also suggest preparing separate environments for each baseline

If there are any other questions, please contact chengyu@nudt.edu.cn or submit an issue.
